services:
  - type: web
    name: fastapi-app
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app"
    envVars:
      - key: PORT
        value: 10000
